version: '3.1'

services:
  html:
    image: cad:1.0.0
    ports:
      - 80:80
    networks:
      - backend

  mongo:
   image: mongo
   ports:
      - 27017:27017
   networks:
     - backend

networks:
  backend: